### ISSUE TITLE
Unresponsive mobile site

### ISSUE THREAD

**Issue by w-miller** [jamesalexatkin/jamesalexatkin.github.io#17]
I can't read your name :(

![Screenshot_20210206-162137](https://user-images.githubusercontent.com/14925373/107131485-af633c00-68ce-11eb-8dca-c8034b0ce651.jpg)

**Comment by w-miller** [comment]
Any update on timescales for this? I've been trying to stall the customer but they're pestering for a release for this bugfix. They really just want to be able to find out what your name is.

**Comment by jamesalexatkin** [comment]
Fixed in !34
